"""Metric definitions and helpers for voice session observability.

All metrics are recorded as Langfuse span metadata or trace-level metadata.
This module provides constants and helper functions for consistent metric naming.
"""

from __future__ import annotations

# ─── Latency Metrics (ms) ────────────────────────────────────────
# Recorded as span durations or explicit metadata fields.

EIBC_TO_FSB = "eibc_to_fsb_ms"
"""End of Input Buffer Committed → First Speech Byte.
The headline metric: full round-trip from user done speaking to agent audio starts."""

VAD_SPEECH_ONSET_LATENCY = "vad_speech_onset_latency_ms"
"""Time from audio chunk received to speech-detected event."""

VAD_SPEECH_OFFSET_LATENCY = "vad_speech_offset_latency_ms"
"""Time from last speech chunk to end-of-speech decision."""

STT_LATENCY = "stt_latency_ms"
"""Speech segment submitted → transcript returned."""

EOT_DETECTION_LATENCY = "eot_detection_latency_ms"
"""Transcript received → end-of-turn confirmed."""

LLM_TTFT = "llm_ttft_ms"
"""LLM request sent → first token received."""

LLM_TOTAL_LATENCY = "llm_total_latency_ms"
"""LLM request sent → last token received."""

TTS_TTFB = "tts_ttfb_ms"
"""Text sent to TTS → first audio byte received."""

TTS_TOTAL_LATENCY = "tts_total_latency_ms"
"""Text sent to TTS → last audio byte received."""

INTERRUPT_LATENCY = "interrupt_latency_ms"
"""User speech onset → clear signal sent to client."""


# ─── Quality / Usage Metrics ────────────────────────────────────
# Recorded as span metadata per turn.

STT_CONFIDENCE = "stt_confidence"
"""STT transcription confidence score [0.0, 1.0]."""

LLM_INPUT_TOKENS = "llm_input_tokens"
"""Tokens sent to LLM per turn."""

LLM_OUTPUT_TOKENS = "llm_output_tokens"
"""Tokens generated by LLM per turn."""

LLM_MODEL = "llm_model"
"""Model used for this generation."""

TTS_PROVIDER = "tts_provider"
"""Which TTS provider was used (azure / elevenlabs)."""

TTS_CHARACTERS = "tts_characters"
"""Number of characters synthesized."""

USER_TRANSCRIPT = "user_transcript"
"""Full user input text."""

AGENT_RESPONSE_FULL = "agent_response_full"
"""Full agent response text."""

AGENT_RESPONSE_HEARD = "agent_response_heard"
"""Truncated text user actually heard (if barge-in)."""

NOISE_FILTERED = "noise_filtered"
"""Whether transcript was filtered as noise."""

EOT_CONFIDENCE = "eot_confidence"
"""End-of-turn classifier confidence [0.0, 1.0]."""


# ─── Session-Level Metrics ──────────────────────────────────────
# Recorded on the Langfuse trace.

SESSION_DURATION = "session_duration_ms"
"""Total session wall-clock time."""

TURN_COUNT = "turn_count"
"""Number of completed conversation turns."""

BARGE_IN_COUNT = "barge_in_count"
"""How many times user interrupted agent."""

FUNCTION_CALL_COUNT = "function_call_count"
"""Number of tool calls executed."""

AVG_EIBC_TO_FSB = "avg_eibc_to_fsb_ms"
"""Average round-trip latency across turns."""

ADAPTER_TYPE = "adapter_type"
"""Exotel / browser."""

SPECULATION_HIT_RATE = "speculation_hit_rate"
"""Percentage of speculative responses that matched."""
